services:
  api:
    build: ./api
    container_name: pokedex-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  app:
    build: ./app
    container_name: pokedex-app
    ports:
      - "4200:80"
    depends_on:
      - api
